name: ci

on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  docker-build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 1200
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set variables
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
          echo "USER=romancin" >> $GITHUB_ENV
          echo "REPO=rutorrent" >> $GITHUB_ENV
        working-directory: ./
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image (master branch)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/aarch64
          push: true
          tags: |
            ${{ env.USER }}/${{ env.REPO }}:0.9.8-${{ env.VERSION }}
            ${{ env.USER }}/${{ env.REPO }}:latest
          build-args: |
            BASEIMAGE_VERSION=3.14
            RTORRENT_VER=v0.9.8
            LIBTORRENT_VER=v0.13.8
            MAXMIND_LICENSE_KEY=${{ secrets.MAXMIND_LICENSE_KEY }}
        if: github.ref == 'refs/heads/master'
      - name: Build Docker Image (develop branch)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/aarch64
          push: true
          tags: |
            ${{ env.USER }}/${{ env.REPO }}:develop-${{ env.VERSION }}
            ${{ env.USER }}/${{ env.REPO }}:develop
          build-args: |
            BASEIMAGE_VERSION=3.14
            RTORRENT_VER=v0.9.8
            LIBTORRENT_VER=v0.13.8
            MAXMIND_LICENSE_KEY=${{ secrets.MAXMIND_LICENSE_KEY }}
        if: github.ref == 'refs/heads/develop'

  update-docherhub-readme:
    runs-on: ubuntu-latest
    needs: docker-build-image
    if: success() && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set variables
        run: |
          echo "USER=romancin" >> $GITHUB_ENV
          echo "REPO=rutorrent" >> $GITHUB_ENV
        working-directory: ./
      - name: Update Docker Hub README
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.USER }}/${{ env.REPO }}
          #short-description: ${{ github.event.repository.description }}
